[toolchain]
package_manager = "bun"

[features]
resolution = true
skip-lint = false

[programs.localnet]
txguard = "FxYDzyGPggfBeQsoLCJqmhAq9danG1qQJXaUjrWTwhp1"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "bunx --bun ts-mocha -p ./tsconfig.json -t 1000000 \"tests/**/*.ts\""
